name: Docker Image CI



on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Print-Use Secret
      env:
        super: ${{ secrets.MYSECRET }}
      run: |
        echo "fuck off"
        echo "hello this is my secrete: ${super}"
