name: Docker Image CI



on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Print-Use Secret
      env:
        super: ${{ secrets.MYSECRET }}
      run: |
        echo "hello we want to see the super secret: ${super}"
        echo "hello we demand to see the github secret: ${{ secrets.MYSECRET }}"
        echo "Hello - we want to use DB Secretfor PROD/DEV ${{ secrets.DB }}"
